### PR TITLE
Removed redefinition of @[JSON::Field(key: "s")]

### PR DESCRIPTION
**Pull request by dineshgadge**
This was failing in crystal v0.36.0 as @[JSON::Field(key: "s")] is already annotated in Binance::Responses::Websocket::Data

### CODE REVIEW

**Review by mwlang — APPROVED** [review]
@dineshgadge Thank you for your contribution to this project!  I wasn't monitoring for PRs before now, so completely missed your submission before now.  All looks good and I see why you pulled "api" out of the base and added directly on the endpoint.  Good decision there.

**Comment by mwlang** [comment]
@dineshgadge Would you be willing to rebase this to the current master?  I will merge once the conflicts are resolved.  Your changes otherwise look good to me.

**Comment by dineshgadge** [comment]
@mwlang I totally forgot that I had raised a PR from master and kept pushing commits related to a side project I was working on. However, if the changes look good to you, I'll rebase to current master and push again after resolving the conflicts.

**Comment by dineshgadge** [comment]
Done. Conflicts have been resolved. Also made the change to the new api `base_url` method you had defined elsewhere to not use `/api`

**Review by mwlang — APPROVED** [review]
Nicely done!

**Comment by mwlang** [comment]
@dineshgadge Thank you for this PR.  I see we picked up a few things with margin orders and such along the way, which is all good, esp. as I don't use those API's myself.

**Pull request merged**
